project_id = "sfwixplzeqooqdavdfoo"

[functions.opensea-listings]
verify_jwt = false

[functions.staking-points]
verify_jwt = false

[functions.opensea-nft-image]
verify_jwt = false

[functions.opensea-collection-nfts]
verify_jwt = false

[functions.staking-points-batch]
verify_jwt = false
